version: '3.8'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .dev/zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ates_network

  kafka:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .dev/kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - ates_network

  mongo:
    image: mongo:4.2
    ports:
      - 27018:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .dev/mongo/:/data/db/
    networks:
      - ates_network

  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    volumes:
      - .dev/postgres/:/var/lib/postgresql/data
    networks:
      - ates_network
    environment:
      POSTGRES_PASSWORD: ates

  elasticsearch:
    image: elasticsearch:7.6.0
    platform: linux/amd64
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .dev/elasticsearch/:/usr/share/elasticsearch/data/
    networks:
      - ates_network

  redis:
    image: redis:latest
    ports:
      - 6380:6379
    networks:
      - ates_network

networks:
  ates_network:
    name: ates